Symfotest\TestBundle\Entity\Comments:
    type: entity
    table: null
    repositoryClass: Symfotest\TestBundle\Entity\CommentsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: '255'
        date:
            type: date
            length: null
            gedmo:
                timestampable:
                    on: create
        site:
            type: string
            length: '255'
        comment:
            type: text
            length: null
        rating:
            type: integer
            length: '2'
        status:
            type: smallint
#        slug:
#            type: string
#                length: '255'
#                gedmo:
#                    slug:
#                        fields: author
    lifecycleCallbacks: {  }
