Symfotest\TestBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        author:
            type: string
            length: '255'
        body:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
