# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Symfotest\TestBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [SymfotestTestBundle]]