# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.comments:
        class: Symfotest\TestBundle\Admin\CommentsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comments" }
        arguments:
            - ~
            - Symfotest\TestBundle\Entity\Comments
            - ~
        calls:
            - [ setTranslationDomain, [SymfotestTestBundle]]

    sonata.admin.users:
        class: Symfotest\TestBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Users" }
        arguments:
            - ~
            - Symfotest\TestBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [SymfotestTestBundle]]