# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Symfotest\TestBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Symfotest\TestBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [SymfotestTestBundle]]
    sonata.admin.comments:
        class: Symfotest\TestBundle\Admin\CommentsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comments" }
        arguments:
            - ~
            - Symfotest\TestBundle\Entity\Comments
            - ~
        calls:
            - [ setTranslationDomain, [SymfotestTestBundle]]