#symfotest_test:
#    resource: "@SymfotestTestBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation

#acme_website:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
#    prefix: /

#_welcome:
#    pattern:  /
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }

main:
    path:      /main
    defaults:  {_controller: SymfotestTestBundle:Page:index}

show_all:
    path:      /show-all
    defaults:  {_controller: SymfotestTestBundle:Page:showAll}

show_author:
    path:      /show-author{author}
    defaults:  {_controller: SymfotestTestBundle:Page:showAuthor, author: Nazar}

show_site:
    path:      /show-site{site}
    defaults:  {_controller: SymfotestTestBundle:Page:showSite, site: site.com}

create:
    path:      /create
    defaults:  {_controller: SymfotestTestBundle:Default:create}

create_post:
    path:      /create-post
    defaults:  {_controller: SymfotestTestBundle:Default:createPost}

# ->2.1. STEP 1: DEFINE SONATAADMINBUNDLE ROUTES
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin