symfotest_user:
    resource: "@SymfotestUserBundle/Resources/config/routing.yml"
    prefix:   /

symfotest_test:
    resource: "@SymfotestTestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /

_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

main:
    path:      /main
    defaults:  {_controller: SymfotestTestBundle:Page:index}

show_all:
    path:      /show-all
    defaults:  {_controller: SymfotestTestBundle:Page:showAll}

show_author:
    path:      /show-author{author}
    defaults:  {_controller: SymfotestTestBundle:Page:showAuthor, author: Nazar}

show_site:
    path:      /show-site{site}
    defaults:  {_controller: SymfotestTestBundle:Page:showSite, site: site.com}

create:
    path:      /create
    defaults:  {_controller: SymfotestTestBundle:Default:create}

create_post:
    path:      /create-post
    defaults:  {_controller: SymfotestTestBundle:Default:createPost}

# ->2.1. STEP 1: DEFINE SONATAADMINBUNDLE ROUTES
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

control_panel:
    path: /admin

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

login:
    pattern:   /login
    defaults:  { _controller: SymfotestTestBundle:Security:login }
login_check:
    pattern:   /login_check
