app:
    resource: @AppBundle/Controller/
    type:     annotation


acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /

hello:
    path:      /hello/{firstName}/{lastName}
    # uses a special syntax to point to the controller - see note below
    defaults:  { _controller: AppBundle:Hello:index }